### ISSUE TITLE
Can Not Create New Relationship 

### ISSUE THREAD

**Issue by degan6** [monicahq/monica#1111]
I can't seem to create a new relationship. 

The page loads for a split second then the errors on the side occur.  I'm not familiar with vue to troubleshoot so if there are any other steps you need to do let me know.

I'm on commit bb87ef8 and PHP 7.2 and Chrome Stable (65.0.3325.181)

![screenshot](https://i.imgur.com/Qe1ybpf.png)

**Comment by djaiss** [comment]
Checking master is dangerous :-)

We haven't fixed this yet... you are missing `global_relationship_form_new_contact: ` in your app.js, after line 217.

Like so

![image](https://user-images.githubusercontent.com/61099/38469836-1822bae4-3b29-11e8-8d76-bc05c9ebd1c7.png)

This will be fixed in the next push to master.
