### ISSUE TITLE
Add friends to a contact

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#117]
Feedback from user:

It would be great to be able to add friends of a contact... so people that you've met once or twice (at your friend Steve's birthday party, for example), you don't know them enough to add as contact but you want to remember their name and where they work, etc. And it's essential that they are somehow connected to the person you know so you can look them up easily next time you go to Steve's party.

**Comment by erdmenchen** [comment]
Instead of adding another (limited) subclass of a contact (like the spouse or the child class), just allow to connect people with relations and add the ability to create a new person when adding a relation to a person.

Workflow for Steves´s party:
- Create the event/activity on Steve´s profile
- Instead of adding additional existing people to the party activity, create a new person and its relation to Steve right beside the activity

This would allow to later revisit Steve, see his relations to other peoples and also (since they have a full profile) add more information about them later on.

**Comment by degan6** [comment]
I love this idea but agree with @erdmenchen make everyone a contact and just link them together in different ways.

**Comment by unformatt** [comment]
+1 for @erdmenchen's approach

**Comment by djaiss** [comment]
This has been done and is merged.
