### ISSUE TITLE
Ambiguous terms

### ISSUE THREAD

**Issue by yarons** [monicahq/monica#1180]
https://github.com/monicahq/monica/blob/9a5114943756a7a14f84c740d6884aebe8100b99/resources/lang/he/app.php#L17
https://github.com/monicahq/monica/blob/9a5114943756a7a14f84c740d6884aebe8100b99/resources/lang/he/app.php#L18

These two are really ambiguous, what do they mean? Where are these used?

For example:
This is for me.
For 48 hours straight.
In Hebrew they are handled differently.

Regarding new, I need to know what is the context because of gender biased terms, a new dress in Hebrew will be different than a new car, the word "new" will be Hadasha for a dress and Hadash for a car.

BTW I already asked for clarification in Crowdin and there was no answer so far.

Thanks!

**Comment by dancyfits** [comment]
#### preposition
עֲבוּר
for, for the sake of, because of
בִּשְׁבִיל
for, for the sake of
בְּגִין
for, for the sake of
כְּנֶגֶד
against, opposite, contrary to, for, facing
בְּשֶׁל
because of, for
בִּמקוֹם
instead of, for, in place of, in lieu of, vice
לְ-
to, for, toward, towards, unto, upon
בְּעַד
for, in favor of, on behalf of, for the sake of
בִּגלַל
because of, due to, for, owing to, on account of
לְשֵׁם
for, for the sake of
### conjunction
כִּי
because, for
בְּ-
for
לְמַעַן
for, in order to
בְּדֵי
for

Oh man.  There might not be a straightforward solution for this.  I'll start searching for ("בְּ"- or "בְּדֵי"?!?) contexts that might necessitate different translations.

Side note: Being fluent in both Hebrew and English is one of the most impressive abilities in my opinion.  Learn Mandarin or Japanese and I'll preorder your autobiography.

**Comment by yarons** [comment]
LOL!
Well, the second option you proposed is seldom used, just tell me what are the options and where can I find this term in context and I'll see what I can do :smile: 

Regarding the side note: I can both read and speak some Japanese but I'm far from fluent.
I find Amharic more appealing for some reason so I put more efforts there in addition to Russian and Arabic which are widely spoken in Israel so you can just try and decipher them while talking to friends :smile:

**Comment by asbiin** [comment]
Well, actually this two words... are not used in the application!
I wanted to check for every texts to translate if they are used, because I know some are not necessary. For now.

**Comment by dancyfits** [comment]
Yeah, it looks like for is used exclusively in comments and for loops, and new is either used for classes or already translated individually.

We'll just have to keep an eye out for new for's and new's. /baddadjoke
