### ISSUE TITLE
Enable editing of calls

### ISSUE THREAD

**Issue by fmcpherson** [monicahq/monica#1271]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

**Describe the solution you'd like**
Currently you can log phone calls but there is no ability to edit what you enter after you save a call. You can edit activities and notes, so I find it odd that you cannot edit logged calls. One should be able to edit any item one enters. Right now the only work around is to delete a call and then re-create it.

**Comment by turtles2** [comment]
@djaiss This would be easy enough to implement. The question is would you rather the Edit be in a Modal like creating is or in-line like notes are?

**Comment by djaiss** [comment]
@fmcpherson of course we should be able to edit calls - but we haven't done it yet 😀  Lack of time.

@turtles2 I actually don't know what would be best here. The problem is that adding a phone call is not in Vue right now, it's plain old Jquery with full page reload. The best would be to rewrite it with Vue, but, well, while it's an easy task, it's also a bit time consuming. All this to say that it would be better I think to do inline editing.

**Comment by djaiss** [comment]
Indeed, duplicate.
