### ISSUE TITLE
Deleting a user results in a broken self-hosted app

### ISSUE THREAD

**Issue by superstrong** [monicahq/monica#1354]
**Describe the bug**
After deleting a user, the users screen still displays fine. I can proceed to delete more users or modify users.

**Screenshots**
This is what the app looks like after I've deleted a user and left the users screen. https://dsh.re/4910d

**Which version are you using:**
 - Hosted Monica v. 2.1.1  on Heroku

**Additional context**
The app works again if I restore the DB (ClearDB) to a version that existed before I deleted the contacts.

**Comment by tomzx** [comment]
So you're saying that all you see rendered on the page is the few items in the screenshot?

**Comment by superstrong** [comment]
@tomzx Sorry, had the wrong screenshot. I replaced the link. That's what I see after I click away from `/people/*` in this scenario.

**Comment by tomzx** [comment]
@superstrong Would you mind either turning on `APP_DEBUG=true` (if it is not a production environment) or looking at the logs in `laravel.log`?

**Comment by superstrong** [comment]
@tomzx Hmm, I do not have a `laravel.log` file anywhere. I'm also not sure how to reliably turn on debug mode in Heroku, as my understanding is there's no direct access to the dyno.

**Comment by tomzx** [comment]
@superstrong They appear to have something, see https://devcenter.heroku.com/articles/exec. Although it appears you can't use that for "one-off" dyno (see https://devcenter.heroku.com/articles/exec#connection). You could look into using https://devcenter.heroku.com/articles/exec#copying-files-from-a-dyno to attempt to copy the file to your computer.

I'm not familiar with the deployment procedure to heroku, but you'd want to modify the `.env` file so that it says `APP_DEBUG=true`, so that instead of seeing the page you see, it will render a stack trace instead (which should also have ended up in the log files).

**Comment by djaiss** [comment]
@superstrong is this still an issue? how can we help?

**Comment by superstrong** [comment]
@djaiss Unfortunately I was not able to pursue debugging further because it got too far out of my comfort zone. Overall, I found that the docs for self-hosting fell a little short in guiding through the Heroku version.

If you follow the instructions to set up a Heroku/ClearDB self-hosted version of the app, I suspect you'll run into the same bug. Perhaps someone else with more expertise can assist with tracing the bug in order to figure out the fix.
