### ISSUE TITLE
Import contacts (iOS vcf format) runs infinitely

### ISSUE THREAD

**Issue by cruisemaniac** [monicahq/monica#1369]
![Uploading Screen Shot 2018-05-21 at 9.05.13 PM.png…]()
The contacts import task (run from `php artisan queue:work`) doesnt want to stop.

Post killing it with `^C`, I know have a few thousand copies of each contact. Is there a way I can debug this?

Screenshot attached for reference.

**Comment by djaiss** [comment]
Which version are you using? This shouldn't happen anymore since 2.1.1.

To debug you can check your logs in `storage/logs` if you have setup the logs in your `.env` file (`LOG_CHANNEL=daily` for instance).

You can also check what is happening in the db, in the tables `failed_jobs` or `jobs`, and see what's going on here.

**Comment by cruisemaniac** [comment]
@djaiss I'm on `tags/1.6.2` per the link here: [Wiki](https://github.com/monicahq/monica/wiki/Installing-Monica-on-Ubuntu).

Perhaps the wiki should also be updated? The Release page shows 2.1.1. But since I was in a hurry setting it up for someone, I just went with Copy - Paste! My bad???

**Comment by cruisemaniac** [comment]
@djaiss I moved my installation to `tags/v2.1.1` and the behaviour still persists.

I've done a reset all your data from the account settings page and started an import again.

Can you tell me if I'm missing some portion of the process?

**Comment by cruisemaniac** [comment]
This error still remains

**Comment by asbiin** [comment]
This should be fixed now.
