### ISSUE TITLE
Getting error: too many redirects

### ISSUE THREAD

**Issue by YPCrumble** [monicahq/monica#15]
Thanks for building this!

Here's what I did:

1. Sign up for an account
2. Play around, create a friend, etc.
3. Read the changelog
4. I was stuck - the header wouldn't take me back so I clicked "Login" (there should have been some way to get back to the main app)
5. After clicking login I can't get in at all and getting the too many redirects error.

**Comment by djaiss** [comment]
Damn it happens to me too sometimes. For the sake of me I don't know why. I'll investigate.

**Comment by djaiss** [comment]
Damn it happens to me too sometimes. For the sake of me I don't know why. I'll investigate.

**Comment by jonasvp** [comment]
It worked for me when accessing '/people' instead of '/'. I'd bet you anything it's an `https`-Redirect gone rogue - happened to me a million times.

Accessing plain `http` will redirect to `https` but the app doesn't recognize it's already on `https` and keeps redirecting. Probably a web server configuration issue. What server are you using? If you like, post the configuration so I can have a look.

**Comment by jonasvp** [comment]
Checking again, it seems it only happens when logged in. So my new bet would be [this middleware](https://github.com/monicahq/monica/blob/master/app/Http/Middleware/RedirectIfAuthenticated.php#L21) misbehaving.

Am I reading it right that you're redirecting to `/` if the user _is_ authenticated? That seems like a good bet for an endless loop. Don't you want to test for the opposite? Or redirect to `/dashboard`?

**Comment by gaurav-sharma** [comment]
@jonasvp is right. See  https://stackoverflow.com/a/32130028/82135. You should redirect to `/dashboard`.

**Comment by djaiss** [comment]
This was indeed the problem @jonasvp Thanks a lot for your help, and @gaurav-sharma for pointing out to the stack overflow article. I'm going to merge the fix.
