### ISSUE TITLE
Can not register for first account

### ISSUE THREAD

**Issue by AGuyNotNamedJon** [monicahq/monica#1549]
**Describe the bug**
When http://example.com/index.php/register is filled out and register button is clicked, it takes me to http://example.com/register. No email sent.
Try to go to http://example.com/index.php/login fill out details, takes me to http://example.com/login.

Both http://example.com/register and http://example.com/login take me to 404 error.

**Which version are you using:**
 - Self hosted Ubuntu 16.04 as advised by instructions (using v2.3.1)

**Comment by AGuyNotNamedJon** [comment]
After a couple reinstallations it started to work, I performed nothing different in the setup procedure.

**Comment by ryanjm** [comment]
@AGuyNotNamedJon - You say that nothing changes in your setup instructions. Do you have any more insight into what might have been different?

I'm running into something similar. I finally got my nginx config file working (I believe it is working properly), but I'm unable to register my first user. I'll go through the registration page and then I'll check the db and no user is added. I'm 99% sure that the configuration for the db is correct since when I did the `php artisan setup:production` it does setup the tables.

I don't get a 404 at `/login`.

**Comment by manojchandrashekar** [comment]
I faced the same issue. Thanks @ryanjm. It was due to folder permissions.
