### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by adrum** [monicahq/monica#162]
Per some discussion in #133, we need to create an issue to foster discussion for the name of the project. The two obvious options are MonicaHQ and Monica. @kstrauser believes "Monica, by MonicaHQ" has a nice ring to it.

While Monica is cleaner (in my opinion), @djaiss wants to address all the feminist remarks he's received and make sure that the name of the project doesn't offend anyone.

**Comment by adrum** [comment]
I'm going to propose a slightly different twist to the name just as an option. I don't know the history behind the name or why @djaiss chose it. I figure I might as well present it, with the full intention of being shot down.

## Story time
I started thinking "How can we name the project so no one gets offended?" I thought we could name it Monico to be gender neutral (my 3 years of high Spanish led me here). Then I thought, "that's awful close to Monaco" (and probably isn't the correct spelling of anyone's name?). 

So decided to look up the history behind the city of Monaco. Excerpt below from [Wikipedia](https://en.wikipedia.org/wiki/Monaco)

> Monaco's name comes from the nearby 6th-century BC Phocaean Greek colony. Referred to by the Ligurians as Monoikos, from the Greek "μόνοικος", "single house", from "μόνος" (monos) "alone, single"[14] + "οἶκος" (oikos) "house",[15] which bears the sense of a people either settled in a "single habitation" or of "living apart" from others. According to an ancient myth, Hercules passed through the Monaco area and turned away the previous gods.[16]

While it's not exact an description of this project, Monaco's name originates from "single house" or "alone, single". This coincidentally describes the use of this project perfectly: to be used by a single person to track their relationships. "Monica is not a social network. It’s not Facebook. It’s for your eyes only." - [monicahq.com](http://monicahq.com/)

## Bonus round

Monaco is a city in France. The project owner/creator @djaiss, is from Quebec, Canada, which has a rich French heritage (or [so I've read](https://en.wikipedia.org/wiki/Quebec)).

**Comment by kstrauser** [comment]
To be clear, I have no strong opinions on this at all. I don't quite get how "Monica" is offensive, but:

1. I believe people who are offended are sincere about it,
2. It's not the name _I_ chose and I don't have an emotional attachment to it, and
3. If it were my project, the name (absent some deep personal connection) would not be the hill I would choose to die on and I'd probably change it.

That said, I'm not @djaiss. If he absolutely loves the name, I'm not going to try to talk him out of it.

My main point earlier was that given the choice between Monica and MonicaHQ, I prefer Monica. There are plenty of "Foo, a Foo Corp. Product" things in the software. Consider Mozilla Foundation and Apache Foundation, for example.

**Comment by theBoatman** [comment]
I would vote for MonicaHQ as the official name as it is easier to google than Monica.

**Comment by arendtio** [comment]
@adrum I read your little story for Monaco, but while I like names with a deeper meaning, I do not find it very suitable :-/ On the other side, Monica is a name many humans have and MonicaHQ is a software for managing the connections between humans, which I find a better match (but does not mean that I am against alternative suggestions in general).

While I can understand that MonicaHQ is more distinct than just Monica I am wondering what that 'HQ' actually means? Headquarters?!? Then I would like to ask why MonicaHQ is better than MonicaApp or MonicaRM (as in CRM). Isn't that what Monica actually is, a 'Relationship Manager'?

I think it would be best if @djaiss could invite a few people who actually have a problem with the current name, as I think we (who are currently participating in this ticket) find the name good and could/would stick with it.

**Comment by djaiss** [comment]
Thanks for this issue.
The main concern is about the gender of the name that has been chosen.

Some context: Monica has been chosen for two reasons:
* This tool reminds me of my previous loved one, it's an hommage to her (Monica was not her name actually) in the sense that I created this tool because she used to be the one in the household to remind me of everything about my friends. When I ended up without her, I wanted to create a tool that did what she was doing: helping me remember.
* Therefore I decided to find a name for this, and I'm a big fan of Friends (the TV show). Monica is a freak that controls all the people's lives and I've found that funny to name this after her.

Now, some people on Twitter and elsewhere have noted that using a female name for this tool is degrading to women, because women are not meant to serve men (which is totally true). This reaction saddens me a bit because I didn't have a single time think of this at any moment and therefore these people judge me for something that I'm definitely not: a mysoginist or something. On the contrary I thought that it was a great sign of respect and showed the upmost importance of the women in my life.

That being said, I'm not a fan of Monaco. If we were to change the name, it should be a gender-less name, or just a generic stuff like the other tools out there (Buffer, Basecamp, whatever). But changing the name now? What would be the impact in terms of marketing? I don't know.

**Comment by cedewey** [comment]
I think that while naming the project Monica wasn't intended to insinuate that women should play the task and relationship manager to men, we live in a society where that messaging and expectation is prevalent. 

Especially in the male-dominated tech world where there is a fixation on building service-oriented apps I can see where this comes across this way.

I also LOVE the project (I only found out about it a couple days ago, but have really enjoyed it so far) and the concept and the principles so I would hate for the name to get in the way of that. The name  and the branding around it is a first impression and since building an inclusive community around the project is important I think a name change branding change is in order.

Also - I think the open-minded responses to the critiques brought forth reflects well on the project. Great thread so far and thanks all for building this thing, it rules. : )

**Comment by cllorca** [comment]
If you ever want to rebrand, I own the trademark for Prsnly which is an app I launched (and ended) that aimed to get people less addicted to the endless feed systems of facebook by allowing them to focus on 1 on 1 (non-instant) messaging / threads. Anyhow, I shut it down because building yet another app was the wrong solution to the problem and since then I've been leaning towards a system just like Monica. 

I would love to lend a hand on this project, so I'm setting up my local server to try to help and contribute. I love this idea and would love to see this take off. Happy to help where possible. Great work everyone who has hacked on this so far.

**Comment by theBoatman** [comment]
Perhaps we can ask the people at Maria-DB or Miranda-IM whether they had negative feedback on their project names.

**Comment by djaiss** [comment]
After a few months, I think the current project name is fine. People seem to remember the name correctly, it's easy to pronounce, etc 😀
