### ISSUE TITLE
Docker fails to start properly

### ISSUE THREAD

**Issue by davidgs** [monicahq/monica#1982]
(Note: you don't need to follow this template, nor to keep headlines or bold sentences - they are just there to guide you. Feel free to delete everything. We review every issue even if we don't immediately respond.)

Thanks for filing an issue and for your interest in the project.

**Describe the bug**
Docker instances don't properly start. Using the latest version, a `docker-compose up` on Mac OS X Mojave results in an endless stream of `monicahq_1  | Waiting for 127.0.0.1:3306 ...` messages. I've tried using the default docker files as-is, and editing them to connect to a locally installed and running (verified) mysql instance. 

**Which version are you using:**
 - Hosting version on https://app.monicahq.com
 - Mobile version
 - A server you maintain yourself (if so, please indicate your current version of Monica)
Davidgs-144:monica davidgs$ git status
On branch master
Your branch is up to date with 'origin/master'.

**Additional context**
I was hoping that I could simply fire this up under docker and have it run, but that appears not to be the case, and, not being a docker expert, I'm not sure what the problem might be.

**Comment by Zero-man** [comment]
Hi David,

From the [Docker installation README](https://github.com/monicahq/monica/blob/master/docs/installation/docker.md):
> Edit .env again to set DB_HOST=mysql (as mysql is the creative name of the MySQL container).

You should use the alias for your `mysql` host as defined in `services` in your docker-compose file, not `127.0.0.1`, since you need to connect to the mysql container's IP, not localhost. If you're using the example docker-compose and .env files they provide, you'll just need to make the .env file change mentioned above.

**Comment by asbiin** [comment]
docker instructions has been updated
