### ISSUE TITLE
Birthday reminders not sent on the day of birthday

### ISSUE THREAD

**Issue by CyberMuz** [monicahq/monica#2024]
Hi,
I noticed strange behavior for the email reminders for birthdays. The email reminders are sent 30 days before the birthday, then 7 days before but there is no reminder sent on the day of the birthday.  Is this a bug? I would like to get the notification on the day of the event so that I don't forget to contact the person.
Also on the today's dashboard there is no indication that there are any events (birthdays) today:

![image](https://user-images.githubusercontent.com/5912703/48318707-aa868380-e604-11e8-99e9-145f148ab52a.png)

I made this screenshots at 2018-11-11 22:45 (my timezone is CET) and my friend has birthday on 11.11.:

For this person the next scheduled reminder is for next year 2019-11-11
![image](https://user-images.githubusercontent.com/5912703/48318736-005b2b80-e605-11e8-96d2-5134f09670bd.png)

I'm using hosted version of the application.

**Comment by Arjenlodder** [comment]
I'm having the same problem with my instance.

**Comment by psteinweber** [comment]
Same issue here. 

That the birthday is not appearing on the dashboard seem to be a bug. This should be displayed - no matter the email reminder preference.

Regarding the emails, it seems to be on purpose that there are 30 day and 7 day reminders though (as it says so in the emails). However for me a same-day reminder would be most helpful. I end up snoozing the emails all the time, some slip through due to that. It would be great if it would be possible to set the preference in regards to when to receive the birthday reminder(s).

**Comment by craigmaloney** [comment]
I'd like to have the birthday shown on the day in the dashboard. Seems a little odd that it doesn't show as a day-specific event for that day.

**Comment by asbiin** [comment]
reminder is sent the day of the birthday.
The issue with displaying birthday on the dashboard is followed on this issue:  #839
