### ISSUE TITLE
Conversation View

### ISSUE THREAD

**Issue by tbirrell** [monicahq/monica#2033]
As of right now (v2.10.1) conversations don't appear to have a view page. Only an edit page. In fact, looking at the code, I can't even find a route or view file for it.

This is inconvenient because if I want to look at a conversation, it sends me to the edit page where it is super easy to mess it up since everything is in an editable field, and it helpfully offers to set the date of the conversation to "today".

I think having a page where you can just view and read through the conversation, without having to worry about messing it up, would be good.

**Comment by Venhaus** [comment]
Also the editing interface is not a particularly nice way to read conversations. Further, to go from one conversation to the next one has to either "cancel" or "update" the current conversation which is rather unintuitive.

**Comment by asbiin** [comment]
This is fixed now

**Comment by jeremies** [comment]
@asbiin, I don't think this should be closed. Since in monicahq.com and in master version of github, when you click a conversation row
![image](https://user-images.githubusercontent.com/18210819/77823508-f9e72a00-70fb-11ea-8068-62c984a45a34.png)
It takes you to the edit view of the conversation and all fields are open:
![image](https://user-images.githubusercontent.com/18210819/77823538-34e95d80-70fc-11ea-81b2-dba393672a90.png)
