### ISSUE TITLE
Upgrade showing non-existant Premium features link

### ISSUE THREAD

**Issue by fly-man-** [monicahq/monica#2220]
After an update of MonicaHQ Open Source version,  Activity type categories and  Features are now Premium features ?

"This is a premium feature that requires a Paid subscription to be active. Upgrade your account by visiting Settings > Subscription."

However, there's no Subscription link in Settings that points to it and why has this "crept" into the Open Source version ??

**Comment by tbirrell** [comment]
I am experiencing the same issue despite the fact that I have `REQUIRES_SUBSCRIPTION=false` in the .env and `account.has_access_to_paid_version_for_free` is set to `1` in my DB. I have dumped the output of `hasLimitations()` and it returns `false` so I suscept the issue is in the Vue component, but I'm not familiar with Vue and have not figured out what it thinks the value of `limited` is

**Comment by tbirrell** [comment]
I think the problem is in `resources/views/settings/personalization/index.blade.php`. Specifically the `limited="{{ auth()->user()->account->hasLimitations() }}"` portions of the component tags. I think what is happening is that `hasLimitations()` is returning the correct value, but it is getting passed in as a string and then cast to a boolean. The issue, therefore, being that a string naturally resolves as true, regardless of the value of the string. 

I'm still digging around the code, but for those who host their own instance and want a quick fix, remove the `limited="{{ auth()->user()->account->hasLimitations() }}"` portions of the component tags. `limited` currently defaults to false, so it should go back to the expected behavior once we stop trying to pass in the value from outside.

**Comment by djaiss** [comment]
Really sorry this happened.
We are going to fix this asap and make a new release.

**Comment by djaiss** [comment]
This has been fixed. Also, #2239 which should fix related stuff. I'm creating a new release right now and it will be ready in an hour. Sorry people, really.
