### ISSUE TITLE
Family relations are not shown correctly, e.g. a female father. 

### ISSUE THREAD

**Issue by simonszu** [monicahq/monica#2309]
**Describe the bug**
Create a person with gender "female". Assign this person as another person's "father/mother". The first contact is shown as the second person's father on the second person's detail page. It should be shown as "mother" instead. 

**Additional context**
Both persons were imported via a vCard set which had no gender information. The gender was added later. 

I understand that the automatic determination of brother/sister or father/mother cannot work for non-binary people, so maybe an auto-determination is not the best idea. Maybe just add a distinct entry in the dropdown for selecting family relations.

**Comment by OrinSafko** [comment]
I noticed this the other day too. Thanks for reporting it. Auto determination would be great, but I see what you're saying regarding non-binary people. Additionally, genders are completely customizable in the system. For instance, I renamed man / woman to male / female. So I don't think this could be automated. I'm for the selection of distinct family relations. I would also ask that in-law status be an option. For instance, I would like my wife to be my Mom's "daugther in-law" rather than "daughter". As of now, when I look at my Mom's contact, it show's my wife as "son" on the sidebar :-)

**Comment by mauirixxx** [comment]
just did a fresh installation, and came here to report the father/son oddity as well. I put my wife and her mothers information in, and it's really weird seeing her mom listed as "father" or my wife listed as "son" :D

**Comment by OrinSafko** [comment]
@simonszu Agreed!

**Comment by asbiin** [comment]
The main issue #1981 will resolve this.
