### ISSUE TITLE
How to properly backup docker container?

### ISSUE THREAD

**Issue by ROODAY** [monicahq/monica#2355]
I followed the instructions to run Monica and mysql docker containers via docker-compose, and I have mounted volumes for both of them. My current method of backup is a script that runs daily that zips the mounted volumes for the mysql container and uploads it to Google Drive. However, the volume has been empty ever since I made my container, something I noticed recently. I notice in the Monica dashboard there's an option to export SQL, and that seems be the best option for backing up. Is there a way I can do this automatically via a script on my server? I'd like to be able to generate these SQL dumps and upload them the way I've been doing with the mounted volume.

**Comment by Pitasi** [comment]
If I'm not wrong, the volume is a storage for documents/photos you upload through Monica, so maybe that's why it's empty for you.

About the database volume, you can backup the SQL like this:

**Backup**
`$ docker-compose exec mysql /usr/bin/mysqldump -u root --password=sekret_root_password monica > monica.sql`

**Restore**
`$ cat monica.sql | docker-compose exec mysql /usr/bin/mysql -u root --password=sekret_root_password monica`

inside the directory containing your `docker-compose.yml`, and assuming your mysql service is called `mysql`. Remember to replace `sekret_root_password` with the root password that you can set through environment variables within docker compose :)

**Comment by ROODAY** [comment]
Thanks, that's exactly what I was looking for!

**Comment by chepec** [comment]
Same setup. Except perhaps more recent stack: Monica v2.13, Docker Compose 1.24.0, Docker 18.09.5. I really appreciate OP asking and @Pitasi taking the time to answer so clearly.

I can confirm that using `mysqldump` as described above works.
But restore fails with 
```
$ cat monica.sql | docker-compose exec mysql /usr/bin/mysql -u root --password=sekret_root_password monica
the input device is not a TTY
```

Of course, the containers were up and running at the time (as evidenced by the successful backup operation). I thought perhaps the dump I was trying to restore could be using an old format (it's from an older version of Monica) so I also tried restoring the just-now created dump. But that still gave the same error.

I found [an SO answer](https://stackoverflow.com/a/52854233) that suggested using `docker` (instead of `docker-compose`) to achieve the same thing, and curiously enough that worked:
```
docker exec -i $(docker-compose ps -q mysql) mysql -u root --password=sekret_root_password monica < monica.sql
```

Perhaps someone more well-versed in Docker can explain why the `docker-compose` approach seems to have stopped working.
