### ISSUE TITLE
Show birthday on contact page

### ISSUE THREAD

**Issue by croesch** [monicahq/monica#2358]
Thanks for this nice project!

Sometimes I would like to see the exact birth date of a person and I find it annoying to click `Edit contact information` - instead I would like to have the birth date available for example as tooltip of the age.

I like that I don't have to calculate the age by myself - but still I often need the exact birth date of a person.

**Comment by sid3windr** [comment]
At first glance this would appear to be OK to close, but actually in my opinion it is not complete: if the year is unknown, the birthday is not shown on the contact page (probably because the age can't be calculated). It would be nice to see this, because for many people I still have to click `Edit contact information`  now...

**Comment by asbiin** [comment]
This is fixed now
