### ISSUE TITLE
Boolean SQL Injection in Monica 1.8.2

### ISSUE THREAD

**Issue by om3rcitak** [monicahq/monica#2370]
Information
--------------------
Name: Boolean SQL Injection in Monıca 1.8.2
Affected Software : Monica
Affected Versions: 1.8.2
Vendor Homepage : https://github.com/monicahq/monica
Vulnerability Types : Boolean SQL Injection

Injection Technical Details
--------------------
URL: http://{domain}/{monica_path}/people/search  
Parameter Name: needle
Parameter Type: POST
Attack Pattern: ' or 'ns'='ns

URL: http://{domain}/{monica_path}/people/search  
Parameter Name: accountId
Parameter Type: POST
Attack Pattern: 1 or 1=1

**Comment by asbiin** [comment]
Thank you for your feedback.
This has been fixed by #1318, and is then fixed since version 2.1.1 and higher.

You can see a test [here](https://github.com/monicahq/monica/blob/master/tests/Api/Contact/ApiContactControllerTest.php#L538) for `/api/contact` query which uses the same backend code as `/people/search` (see #1557).

I just don't see how you can exploit the parameter `accountId`? There is no way you can use this parameter to the search request. I will really appreciate some details. Thanks

**Comment by djaiss** [comment]
Closing. Feel free to reopen the issue if there are more discussions around this.
