### ISSUE TITLE
CardDAV wrong vCard Version

### ISSUE THREAD

**Issue by ein-stein-chen** [monicahq/monica#2411]
**Describe the bug**
Exporting a contacts vCard from the web view results in a vCard 4.0.
The CardDAV server provides vCards with Version 3.0.
The only difference between both cards is the 'VERSION' field.

**Which version are you using:**
- Self hosted v1.12.0

**Additional context**
As of [RFC 6350](https://tools.ietf.org/html/rfc6350#page-32) the 'GENDER'-field is only supported in vCard 4.0

**Comment by asbiin** [comment]
This is not a bug.

The default format is VCard 4.0.
The caddav server (sabre) provides vcards with the version you ask it.
This is tested [here](https://github.com/monicahq/monica/blob/master/tests/Api/DAV/VCardContactTest.php#L243) and [here](https://github.com/monicahq/monica/blob/master/tests/Api/DAV/VCardContactTest.php#L282).

So the problem is more likely with the carddav client you use, which should ask VCard version 4.0 if you want it.

The glitch is with sabre (the backend software used to serve carddav), which converts VCard from version 4.0 to version 3.0, and with which the default version (if not specificied) will be [version 3.0](https://github.com/sabre-io/dav/blob/master/lib/CardDAV/Plugin.php#L759). So it's not Monica behavior, but sabre and/or your client behavior.

**Comment by ein-stein-chen** [comment]
So that I understand correctly: The Server has to advertise that it supports vCard 4.0 and then the client either can accept the vCard 4.0 format by sending a `address-data-type content-type="text/vcard" version="4.0"` or version="3.0" or nothing at all in which case it is assumed, that the client also uses vCard 3.0. Source: [1] and [2]

_With this in mind some questions/additions:_
Could i overwriting the default version? More accurate: Is there a way to force sabre to provide only vCard 4.0? (Only for my own instance)

I tested some Clients 'Evolution', 'vDirSyncer' and 'CardBook' (Thunderbird Addon) and as far as I can tell most of them don't support vCard 4.0, which is a pity.
BUT: In this case the solution must not be to send a vCard 4.0 with a diferent Version attribute and keep the other fields the same.
Especially because as far as I know the date format differ between vCard 3.0 and vCard 4.0 and also in vCard 3.0 the gender should be specified by the `X-GENDER` attribute.

[1]  http://sabre.io/dav/building-a-carddav-client/
[2]  https://github.com/pimutils/vdirsyncer/issues/503

Attachment: Screenshot of:
vCard sync:
![vcard_carddavsync_cardbook](https://user-images.githubusercontent.com/17032639/52539906-c9bbbb00-2d83-11e9-9b62-a26f7f72d1be.png)
vCard export: 
![vcard_monicaexport](https://user-images.githubusercontent.com/17032639/52539912-d9d39a80-2d83-11e9-898c-d4dfb0d9dd01.png)

**Comment by asbiin** [comment]
I think this is more an issue vie sabre/dav eventually. Don't hesitate to open an issue on sabre/dav project.
