### ISSUE TITLE
Produce different Logo size

### ISSUE THREAD

**Issue by asbiin** [monicahq/monica#2668]
Our great logo is available [here](https://app.monicahq.com/img/monica.svg).

There is a [140px version](https://app.monicahq.com/img/monica_140.svg), but it's buggy:
![image](https://user-images.githubusercontent.com/25419741/57569266-a17b4100-73f2-11e9-8124-24a793f77583.png)
Could you fix it?

The webmanifest file should include a 192px and 512px icon. See [this doc](https://developers.google.com/web/tools/lighthouse/audits/install-prompt).
We should provide a 192px at least.

**Comment by tbirrell** [comment]
The bug is in the open line of the SVG file. You want to use `height/width` to scale the image, and leave `viewbox` alone. The `viewbox` is the canvas (per se), so you want to scale the canvas rather then resize it.

`<svg width="140" height="140" viewBox="0 0 500 500" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">`
