### ISSUE TITLE
deploy on heroku

### ISSUE THREAD

**Issue by maxventures** [monicahq/monica#2740]
Hi,

amazing project

how do i deploy it to heroku?

is email integration working on self serviced deployment?

thanks

**Comment by tomgs** [comment]
@maxventures 

https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md

Note that the e-mail part (which I wrote last year if I'm not mistaken) might not work, testing it as we speak.

**Comment by tomgs** [comment]
Can confirm the e-mail reminders now work!

Things needed in order to make it work:

1. Follow the instructions in https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md.
2. Add a custom domain in mailgun.
3. Add the "To" and "From" e-mail addresses you're going to use as verified e-mail addresses on mailgun.
4. Upgrading mailgun by entering a credit card (there is no charge, but they do require you enter it so you'll be upgraded.
5. Verify the custom domain via DNS (there are instructions on their site).

Probably should edit this into the docs sometimes, will get to it later.

**Comment by maxventures** [comment]
amazing, will share my experience once deployed internally

**Comment by jantonz** [comment]
> Can confirm the e-mail reminders now work!
> 
> Things needed in order to make it work:
> 
> 1. Follow the instructions in https://github.com/monicahq/monica/blob/master/docs/installation/heroku.md.
> 2. Add a custom domain in mailgun.
> 3. Add the "To" and "From" e-mail addresses you're going to use as verified e-mail addresses on mailgun, and then actually verifying them.
> 4. Upgrading mailgun by entering a credit card (there is no charge, but they do require you enter it so you'll be upgraded.
> 5. Verify the custom domain via DNS (there are instructions on their site).
> 
> Probably should edit this into the docs sometimes, will get to it later.

I would add that the instructions in section **Optional: Setup the access tokens to use the API** are needed in order to emails to be sent by Mailgun.

Additionally, it seems that it is possible to use the Mailgun-provided domain instead of a custom user-provided domain (something like *sandbox3bga92d4efc34faf9547c51522082d0b.mailgun.org*).

**Comment by asbiin** [comment]
> I would add that the instructions in section Optional: Setup the access tokens to use the API are needed in order to emails to be sent by Mailgun.

Why that? I don't see where it is mandatory?

> Additionally, it seems that it is possible to use the Mailgun-provided domain instead of a custom user-provided domain.

You're right. I did successfully used the heroku mailgun app once, and it could be used too.

**Comment by tomgs** [comment]
Can confirm that a sandboxed domain works (though I'm using my own now for some historical unrelated reason).

**Comment by jantonz** [comment]
> > I would add that the instructions in section Optional: Setup the access tokens to use the API are needed in order to emails to be sent by Mailgun.
> 
> Why that? I don't see where it is mandatory?
> 

You are completely right, I confirmed that it is not needed. I must had fixed it with some other change I don't remember.
