### ISSUE TITLE
Bug on reminder

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#305]
Feedback:

The Reminder creation page does not seem to match the list of reminders for the person.

For instance, I created a reminder, which according to the creation form would remind me 1 month prior to an anniversary date to buy a gift.  However, when submitted, the Reminders list for that person seemed to indicate from that date on, every month I'd get a reminder to buy an anniversary gift.

**Comment by yamakadi** [comment]
I'll check it out soon. ><

**Comment by yamakadi** [comment]
Everything is behaving as expected on this end.

I see the issue is though. You named the fields frequency type and frequency number, so I assumed they meant `remind me {frequency_number} times every {frequency_type} with the first reminder on {next_expected_date}` unless it's once, then `remind me once on {next_expected_date}`.

This behavior is exactly the same as the old behavior. Birthday reminders also seem to follow this logic (reflected in the new addBirthdayReminder method as well as the old procedural adding of birthday reminders on addKid/SginificantOther methods). The language on the add reminder page is also supporting this approach.

Am I missing something?

**Comment by djaiss** [comment]
Indeed, this is fixed now. I've changed that - but it was using the date of the current date actually. 

Problem solved, issue closed ;-D
