### ISSUE TITLE
License vs Wording

### ISSUE THREAD

**Issue by iajrz** [monicahq/monica#38]
There's potential confusion because the software is released under the MIT license, which permits, among other things to commercially exploit the software, but the README file asks to not commercially exploit it. Can't have it both ways - either the license needs to be changed or the README's wording removed or changed to make it clear that the request to not use it commercially is a non-binding request.

**Comment by djaiss** [comment]
Good point. Yeah, I need a license where people can use it at will, but can't make money out of this. Which one would it be then?

**Comment by ocdtrekkie** [comment]
AGPL-type licenses will scare off most corporate entities from touching an open source project, since it forces them to open source their work as well. You can always sell the right to keep it closed source, for instance, separately. (Look at 'dual licensing' strategies.)

It is very hard to outright require non-commercial use while remaining "free and open source software", as I don't believe the definition of free software permits you to restrict what it's used for. Creative Commons has non-commercial use requirements, but isn't considered a "software license", and would make whatever you distribute with it not technically free software.

**Comment by williamtheaker** [comment]
Both the [Open Source Definition](https://opensource.org/osd) and the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html) require allowing commercial use so you won't find a free or open source software license that prohibits commercial use. The [Affero GPL](https://www.gnu.org/licenses/agpl.html) has strong copyleft which prevents someone from starting a company based on Monica and not sharing the source code.

**Comment by ocdtrekkie** [comment]
Also, as a pedantic but probably useful point of note: What is currently released with an MIT license file, is arguably permanently available under MIT. If you relicense, whatever code/changes/improvements/versions you make going forward would be available under the new license.

Technically, if they downloaded the code as it stands now, forked it or just hosted it and sold a subscription to it, that'd probably be completely defensible in court.

**Comment by iajrz** [comment]
You can't have free software that isn't available for commercial use; open source software either; @williamtheaker made the point. Now, AGPL would prevent people from gaining an edge off of your work without you being able to nurture your own software from their improvements (MIT doesn't do that for you)... that doesn't prevent you from having people compete with you with your own software, though.

If you want to make this a commercial effort and protect yourself while letting people self-host and improve on the code, I strongly recommend AGPL. Gain customers just the way Automattic does: first class support, hosting, and services built to work with your product. Build your brand, too, and protect it: copyright logos, register your trademarks. So if anyone sells Monica, it has to be Monica - and the brand leads customers to you.

**Comment by iajrz** [comment]
@ocdtrekkie not pedantic at all - it's crucial to note, specially since many people have already forked this.

The MIT License has only _one_ condition, and it doesn't state that the license may be revoked. If a user breaks the license, then the contract is broken and the user has no right to keep acting as if the license is valid, otherwise the rights are retained.

**Comment by djaiss** [comment]
Let's put AGPL for now then. Thanks a lot for all the advices here. It really helps.

Don't get me wrong. I want this to be used by anyone forever for free if they want to install it themselves, but protect my rights too when I'll try to monetize this to sustain it on the long run.

**Comment by djaiss** [comment]
It's now AGPL. Again, many thanks.

**Comment by claar** [comment]
A friend sent me a link to this package today, but the first thing I always do is check the LICENSE... unfortunately, many places can't use GPL software due to policy restrictions.

I respect people's licensing decisions, but folks should realize that using GPL licensing will restrict many folks from using/contributing to your software, and that the Laravel community tends toward the MIT license partially for this reason.

Best of luck in your project!

**Comment by ocdtrekkie** [comment]
@claar That is kinda the point. I am not fond of copyleft licensing myself, but if he wants to limit commercial reuse of his code because he wants to monetize the project himself, it is probably the way to go.

**Comment by claar** [comment]
@ocdtrekkie I agree with you, the interesting part is @djaiss's quote, "but protect my rights too when I'll try to monetize this to sustain it on the long run."

AGPL definitely presents a different playing field when it comes to protection against competitors, since they have to release any improvements to the software. But while it restricts competitors, it equally restricts @djaiss's own monetization options. And while going from MIT to a commercial license is possible, once you go AGPL, there's no going back for code contributed under that license.

**Comment by iajrz** [comment]
AGPL is not a "non-commercial" license -- he'll be able to make money off of it. Will the licensing prevent you from using the software?

**Comment by ocdtrekkie** [comment]
@claar AFAIK, the original creator is free to dual-license their own work. Though I suppose @djaiss might want to make sure any substantial contributors agree to a CLA.

**Comment by iajrz** [comment]
They can dual license their own work -- but would need to exclude the AGPL work by the contributors.

**Comment by ocdtrekkie** [comment]
Yeah, so @djaiss should get a CLA in place. Any of the existing third party contributions arguably are trivial. The largest third party contribution is adding periods to text copy or something.

**Comment by djaiss** [comment]
What about this license instead? https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by iajrz** [comment]
That would prevent _you_ from using contributor's code for commercial purposes.

**Comment by iajrz** [comment]
Let me summarize what AGPL means to you: anyone who makes the service available has to give away the source code. (Which means they can get to see the LICENSE file, and know who the authors are). That includes you. It's not that bad. Reddit's source is readily available, but I don't see any competition based off of it taking away their market niche.

**Comment by ocdtrekkie** [comment]
Basically, the key thing is if you want to be able to have the freedom to use this software the way you want to, even if you accept PRs from the community, you may need to consider a CLA, or Contributor License Agreement, where people who submit the PRs agree to grant copyright ownership of the code to you.

**Comment by Phrohdoh** [comment]
>  And while going from MIT to a commercial license is possible, once you go AGPL, there's no going back, and the whole work is considered AGPL from this point on.

This isn't true.

If all owners agree to relicense their contributions under a different license then the license can change.

If someone doesn't agree to do that you can replace their implementation and license the new implementation as you wish.

**Comment by ocdtrekkie** [comment]
And a CLA just makes that process easier, because you can ensure that people grant the project owner, at contribution time, the right to relicense.

I think there's a huge open source project like a decade old that recently relicensed, and they had a huge ordeal tracking down everyone or replacing code from people who said no or who they couldn't locate. The sooner this is addressed, the easier it is.

**Comment by Phrohdoh** [comment]
FWIW [GitLab CE is MIT licensed](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/LICENSE).
