### ISSUE TITLE
Postgres migration failing

### ISSUE THREAD

**Issue by Sweenu** [monicahq/monica#3957]
I am running a docker-compose with monica 2.17.0 with postgres 11 but I get this error when going through the database migrations:
```
Migrating: 2017_06_07_173437_add_multiple_genders_choices

In Connection.php line 669:

  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"
  LINE 1: ALTER TABLE `contacts` DROP CONSTRAINT `contacts`_gender_che...
                      ^ (SQL: ALTER TABLE `contacts` DROP CONSTRAINT `contact
  s`_gender_check;)


In PDOStatement.php line 119:

  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"
  LINE 1: ALTER TABLE `contacts` DROP CONSTRAINT `contacts`_gender_che...
                      ^


In PDOStatement.php line 117:

  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"
  LINE 1: ALTER TABLE `contacts` DROP CONSTRAINT `contacts`_gender_che...
                      ^
```
Have I missed something? Is postgres 11 even supported?
Thank you :)

**Comment by nwalke** [comment]
Note that the requirements in the readme specifically mention only supporting MySQL: https://github.com/monicahq/monica#requirements

As for why this is, I think it's due to the fact that they're writing the actual alter statements themselves likes so: https://github.com/monicahq/monica/blob/master/database/migrations/2017_06_07_173437_add_multiple_genders_choices.php

Instead of using Laravel's Schema facade + Blueprints: https://laravel.com/docs/7.x/migrations#migration-structure

**Comment by Sweenu** [comment]
Okay I see, I'll go on using MySQL to avoid more problems then.

**Comment by asbiin** [comment]
@nwalke Thanks. You seems to have more knowledge on postgres migrations on Laravel. Would you consider helping us to make Monica compatible with postgres ?
