### ISSUE TITLE
Self Hosted: Notifications and Reminders silently fail to send

### ISSUE THREAD

**Issue by Seth-Rothschild** [monicahq/monica#3973]
**Describe the bug**
No notification or reminder emails have been sending on my account. I'm using the docker container with gmail as smtp server. The *invite someone to your account* email sends as expected, so smtp seems to be configured correctly. 

The associated Google password I've created for Monica has not been accessed since inviting the second user.

The `reminder_outbox` table seems to populate correctly, but `reminder_sent` is empty. I have not seen anything useful in the daily log files, but maybe that's not the place this would show up.

I don't know where to start with debugging this or testing this, but I'd be happy to provide more information if it would be helpful.

**Which version are you using:**
 - A server I maintain myself, docker, (v.2.16.0)

### Edits
The previous title said that reminders were not sending because of the second user. The issue seems to have no relation to existence of a second user.

**Comment by dotcs** [comment]
I have the same issue. In a self-hosted instance with emaila configured correctly (because password forgotten mail works) no mails are sent for Birthday reminders. For me also the `reminder_outbox` table is populated but the `reminder_sent` table stays empty. Is there a batch job or something that needs to be activated? Could not find anything so far in the documentation.

**Comment by Seth-Rothschild** [comment]
@dotcs I still haven't figured it out for sure. It seems from the docker logs that something has "changed" with cron but I can't find any documentation on it or how to set it up other than in issues. 

I'm going to close this, because I'm increasingly convinced it's not a problem with the mail sending but a problem with some scheduled job not running correctly with a default setup.

**Comment by Seth-Rothschild** [comment]
For anyone looking here in the future: the issue was indeed with cron not running in the container. To fix, you can add the environment variable into the docker start command with `--env CRON_LEGACY=true ` which runs `crond -b -l 0`. 

You can check if cron is running by looking at `docker logs monica` where you will see commands like:

```
Running scheduled command: '/usr/bin/php7' 'artisan' send:reminders > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' send:stay_in_touch > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' monica:calculatestatistics > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' monica:ping > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' monica:clean > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' monica:updategravatars > '/dev/null' 2>&1
```
which you would not otherwise see.

**Comment by asbiin** [comment]
There is a reason the cron is not running inside the container anymore, and I strongly recommend not to enable it.
Use another container to run the container, or use supervisord, they are way better in a docker way.

See the [example section](https://github.com/monicahq/monica/blob/master/scripts/docker/.examples/readme.md).

**Comment by dotcs** [comment]
I have also reconfigured my instance yesterday similar to what is shown in the [supervisor + apache example](https://github.com/monicahq/monica/tree/master/scripts/docker/.examples/supervisor/apache) and it does indeed work as expected. <3
I also agree that the `CRON_LEGACY` should not be used. The setup with `supervisord` is still pretty easy but better from a Docker perspective since then `supervisord` is set as the root process which manages everything in the container.

**Comment by peetersdaan** [comment]
Sorry to hijack this post. I'm currently using Portainer which uses two containers (Monica app and DB). I've managed to make it work to add - CRON_LEGACY=true to the environment of my docker-compose.yml. However, I am not able to set up supervisord. Could anyone assist me (even for a small fee) with this?
