### ISSUE TITLE
Reminder Emails are not sent despite emails being able to be sent

### ISSUE THREAD

**Issue by elikoga** [monicahq/monica#4758]
**Bug Description**
I am hosting my Monica Instance on a VPS running YunoHost. I have installed Monica from the 2.19.1 branch of the YunoHost App repository.

Emails are set up to send through the local SMTP server. Running `sudo -u monica php artisan monica:test-email` sends an email.

A cron Job is set up to run Monica by having a file named `monica` in `/etc/cron.d/` containing:
```
* * * * * -u monica /usr/bin/php7.3 /var/www/monica/artisan schedule:run
```
Reminder E-Mails are not sent.

**Comment by mgrhm** [comment]
I’m running my instance on a VPS with Debian 10 installed, which should be a similar system to what YunoHost provides. I don’t have a file called `monica` in `/etc/cron.d/`.

Have you tried [adding the cronjob using crontab](https://github.com/monicahq/monica/blob/master/docs/installation/providers/debian.md#4-configure-cron-job)?

You can do that by running:

    crontab -u www-data -e

and adding the line:

    * * * * * php /var/www/monica/artisan schedule:run >> /dev/null 2>&1

as the last line in the file.

Since doing that, Monica has been happily sending emails for me.

**Comment by elikoga** [comment]
No, I have not tried that as the issue persists if the command is run by hand however I have added it now and will report back in 15 minutes on wether the issue persists

**Comment by elikoga** [comment]
Okay the reminder seems to sends now, I'm gonna try to figure out why the default configured cronjob doesn't work and then maybe raise a stink at https://github.com/YunoHost-Apps/monica_ynh/

Thanks for suggesting it @mgrhm !
