### ISSUE TITLE
true RTL

### ISSUE THREAD

**Issue by yanivz** [monicahq/monica#4760]
in order to make the app true RTL it's not enoghe to put "dir=rtl" in HTML tag, you need to change the attribute in the BODY "text-align: left;" to     **"text-align: right;"** in the CSS file https://app.monicahq.com/css/app-rtl.css?id=8ee9e03a2fc4b4087b8a
that's it, this will make it TRUE rtl site.

**Comment by asbiin** [comment]
Thank you for your report.
The app *has* TRUE rtl. However, there might be some errors, which we could fix, if you give us more details about what's wrong in the design? Where did you find wrong disposition?

It's also possible there is still "text-align: left" in the rtl file because it makes sense. Every text-align may not necessarily be set to "right" in rtl!

**Comment by yanivz** [comment]
![true rtl](https://user-images.githubusercontent.com/4169780/103459405-dcdd2880-4d17-11eb-9c18-50c222694f54.JPG)
![not rtl](https://user-images.githubusercontent.com/4169780/103459406-de0e5580-4d17-11eb-91b4-255b6b52afc9.JPG)
pls see diffrent

**Comment by yanivz** [comment]
i only changed one line code for thia
