### ISSUE TITLE
Bot that closes and locks conversations 

### ISSUE THREAD

**Issue by cabello** [monicahq/monica#4934]
Hi,

I hope you are all doing alright given these times. 💜 

As a developer, I also love some automation. Automation can also be considered aggressive sometimes.

This issue for example: https://github.com/monicahq/monica/issues/33

Was closed without a warning that it was stale or anything, the PR that was merged into main branch was only the start of supporting that feature.

Now me, and any other folx cannot contribute to it. 😢 

Please, consider having a stale comment before closing, locking the conversation, just because an issue is 1 year old it doesn't mean it is not important or it won't ever be worked on.

The other issue from this approach is that if a person searches and find this issue they cannot contribute to it and have to create a duplicate ticket that may not include a link to the original ticket or context.

Cheers,

**Comment by mritzmann** [comment]
To be fair: The issue you mentioned has been closed for more than a year 🙂

In a perfect world, an issue you are working on is always open and assigned to you. This is the easiest way to know that someone is already working on it, otherwise you are doing the work twice. Whether you should reopen old issues or create a new one is something everyone does differently. Monica has decided to create a new issue, which I find completely okay.
