### ISSUE TITLE
30 seconds time out error when importing contacts (vcf 400km, 1200 contacts)

### ISSUE THREAD

**Issue by baldfox** [monicahq/monica#5234]
**Describe the bug**
Importing a vcard (export from Google contacts) of 1200 people results in a whoops error after 30 seconds of importing.
vcf is approx 400kb in size. This is a clean import, no previous contacts there.

**Screenshots**
![image](https://user-images.githubusercontent.com/32448665/119624729-41b23000-be2b-11eb-814b-6db2f1c885b8.png)

Docker:
monica:latest
mysql 5.7

**Comment by mgrhm** [comment]
Not a bug-fix, but have you tried breaking the import into three or four smaller chunks?

**Comment by baldfox** [comment]
> Not a bug-fix, but have you tried breaking the import into three or four smaller chunks?

Do you know how to break apart a vcf to divide it? Happy to try it.

**Comment by mgrhm** [comment]
I don't know how to split an existing VCF into smaller parts.  I did it by exporting my contacts in smaller groups to multiple VCFs.  That was pretty easy in Mac OS's Contacts application -- just highlight as many as I wanted, then select "Export vCard".

Does Google Contacts have the option to export only selected contacts?  If it does, you could do them in smaller batches, like A-F, G-L, and so on.

I also checked this a little more since my last comment, and I don't think the size of the file is causing your issue.  My individual VCFs were bigger than yours because they included photos.  It's possible that the VCF that Google Contacts is producing is somehow not quite right.

**Comment by zeezhao** [comment]
Have you tried increasing "max_execution_time" variable in php.ini & then restart server?

**Comment by baldfox** [comment]
> Have you tried increasing "max_execution_time" variable in php.ini & then restart server?

I hadn't. I didn't even know where that file or line is. I'll try and find it and revert.

**Comment by asbiin** [comment]
You have to activate the queue worker in order to be able to import such a big file.
In that case, the import is handled by the background task, which has no timeout.
