### ISSUE TITLE
"Search your contacts" bar is not working

### ISSUE THREAD

**Issue by sid3windr** [monicahq/monica#557]
(at least for me, I've tried Firefox latest and Chrome latest)

Entering a contact name will provide me with the correct result in the dropdown, but clicking that result does nothing at all, instead of opening the page of the correct contact.

**Comment by HHErebus** [comment]
I was waiting to see if the issue was mine alone or not. What's happening is that the mouse events that trigger the page change to the contact are being sabotaged by the fact that the link itself is removed after 50ms of the blur/focusout event. 
If you show any hesitation on releasing the click, it won't work, the search bar smells your fear 😛 

Jokes aside, this is being done in resources/assets/js/search.js, on line 146. In my case, upping the timeout from 50 to 150 solved this. I can submit a PR midway next week, or you can, whatever suits best :)

**Comment by sid3windr** [comment]
You're right, I managed to actually navigate to a contact 1 out of 8 tries now. So at least there is an idea of it working...

**Comment by djaiss** [comment]
I'll try to provide a fix tonight (if @HHErebus is right about the solution) 😀

**Comment by djaiss** [comment]
That should be fixed now. In production at least. I'll push a new release at the end of the week with other stuff.

**Comment by sid3windr** [comment]
Works for me!
