### ISSUE TITLE
Cant Create a New User Account!

### ISSUE THREAD

**Issue by yoginth** [monicahq/monica#667]
While I create a new account, Monica throwing an error like` Whoops, looks like something went wrong.`

**Comment by djaiss** [comment]
@yoginth Hum. Have you ran
* migrations: `php artisan migrate`
* installed Oauth keys: `php artisan passport:install`
* linked the avatar folder:  `php artisan storage:link` 

?

**Comment by tristankerner** [comment]
I'm not sure if it's related, but I just installed Monica for the first time a few days ago, and received a similar error when registering. I turned on debugging, and it turned out that my issue was because I hadn't set up the email account/notifications in the .env file, and it was causing this error:

`Swift_RfcComplianceException thrown with message "Address in mailbox given [ValidEmailAddress] does not comply with RFC 2822, 3.6.2."`

`/var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php`

It worked fine after I actually set up the email credentials.

**Comment by yoginth** [comment]
fixed!
