### ISSUE TITLE
Adding a note doesn't work.

### ISSUE THREAD

**Issue by Nebucatnetzer** [monicahq/monica#679]
When I try to add a note to a contact with the new form I get this error from the JavaScript console.
```
Blocked loading mixed active content "http://monica.2li.ch/people/71/notes"
```
I'm running Monica behind an Apache Reverse Proxy.

**Comment by djaiss** [comment]
@Nebucatnetzer looks like an error from http to https or vice-versa.
Have you configured the Url properly in your `env` file?

**Comment by Nebucatnetzer** [comment]
I think so:
```
APP_URL=https://monica.2li.ch
```

**Comment by Nebucatnetzer** [comment]
@djaiss I'm not really familiar with Laravel but are we maybe missing something like this?
https://laravel.com/docs/5.5/requests#configuring-trusted-proxies

Or is this something that can get added individually?

**Comment by djaiss** [comment]
@Nebucatnetzer unfortunately I don't know the impact this would have if I added this to the codebase. It'd be awesome if the community could help here, because I don't have the answer to your question 😢

**Comment by Nebucatnetzer** [comment]
Just for reference :)
I searched around a bit today but wasn't really able to find much related information.
Adding the TrustedProxies file on its own didn't change anything. I reckon one needs to reference/include it somewhere.

As for information related to Vue.js behind a reverse proxy I basically found nothing at all.

**Comment by tristankerner** [comment]
As far as I know, the "blocked loading mixed active content" is a client/browser based error caused by loading/accessing an HTTP resource on an HTTPS page. I'm not familiar with Apache Reverse Proxy, but I believe the theory is that all client traffic should be routed through the reverse proxy, and be HTTPS from the client perspective. On the servers side, traffic may be routed around in other ways, but that should be invisible to the client and it shouldn't cause an error like this. 

Any form using Vue.js/Axios/AJAX is sending a request from the client's browser, to the server, and that request should be taking place via an HTTPS endpoint. If this request were successfully done via the attempted "http://monica.2li.ch/people/71/notes" URL, the content of that form submission would be unencrypted).

The goal should probably be to identify why a plain HTTP request is being attempted from the client side, and change it to HTTPS. My initial thought is that there may be a configuration error, either in the reverse proxy, or the server software that is causing the URL to be redirected to plain HTTP for the client, instead of going through HTTPS like it should.

Just to confirm, you received this error when viewing the page in HTTPS (i.e. https://monica.2li.ch/people/71/ )?

**Comment by djaiss** [comment]
FYI on my machines, wether the .com version or my dev environment, the page is in HTTPS and I have no issues with mixed content.

**Comment by Nebucatnetzer** [comment]
@tristankerner yes I access my Monica instance through HTTPS. The connection between the proxy and Monica is not encrypted.
I'm using the proxy config for quite a few servers so I doubt that the proxy config is the problem. However I could be wrong I'm not really that experienced with Apache.

My guess would be that I'm missing a setting in Monica which tells it to write all URLs to HTTPS.

**Comment by djaiss** [comment]
> My guess would be that I'm missing a setting in Monica which tells it to write all URLs to HTTPS.

This is done here https://github.com/monicahq/monica/blob/master/routes/web.php#L13

Have you put `APP_ENV` to `production` in your .env file?

**Comment by Nebucatnetzer** [comment]
@djaiss yes it's set to production.

**Comment by tristankerner** [comment]
@Nebucatnetzer I really can't see anything inside Monica that would cause this to happen. The AJAX endpoint is relative to the current URL, so if you're on a secure page, the javascript request should be sent to the secure URL. In production, the routes themselves don't really exist via http. Here are some additional questions that may help:

- Are you using the latest version of Monica?
- How was Monica installed (i.e., generic, docker, etc)?
- Can you post any Apache Reverse Proxy configuration lines pertinent to your installation of monica (redacting any potentially sensitive information as needed)?

**Comment by Nebucatnetzer** [comment]
I'm using version 1.4.1 and it's installed "natively" on a Debian Stretch server.

This is the reverse proxy config for Monica.
```
<VirtualHost *:80>
        RewriteEngine on
        ReWriteCond %{SERVER_PORT} !^443$
        RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [NC,R,L]
        ServerName monica.2li.ch
</VirtualHost>

<VirtualHost *:443>
    ServerName monica.2li.ch
    SSLEngine On
    SSLProxyEngine On
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    SSLHonorCipherOrder on
    SSLProtocol all -SSLv2 -SSLv3 -TLSV1
    SSLCertificateFile /path/to/cert.crt
    SSLCaCertificateFile /path/to/cert.crt
    SSLCertificateKeyFile /path/to/cert.key
    <IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
    </IfModule>
    ProxyPreserveHost On
    ProxyPass / http://monica.2li.local/
    ProxyPassReverse / http://monica.2li.local/
</VirtualHost>
```

**Comment by djaiss** [comment]
@Nebucatnetzer have you tried with the awesome patch @mwalling has submitted?

**Comment by Nebucatnetzer** [comment]
I'll give it a go later. Thank you for letting me know.

**Comment by Nebucatnetzer** [comment]
@djaiss I reckon this commit isn't in version 1.5.0 right?
I'm asking because in 1.5.0 I can't add notes.
When I want to checkout master I get the same problem as @Kovah mentioned here:
https://github.com/monicahq/monica/commit/8a96eac41afd81a0f94cf59ba29319466c1d205f

**Comment by Nebucatnetzer** [comment]
I installed version 1.6.2 today and the notes are working again. Just for the record.
