### ISSUE TITLE
People need more metadata

### ISSUE THREAD

**Issue by degan6** [monicahq/monica#76]
Most people have more than one email and phone number, plus websites, twitter username. 

I think adding something were we have a either a table for each type of data like the email table, address table, phone number table and so on. That might not scale well so an alternative is to make a general person metadata table and have a name and value column relating to one person. 
The second approach isn't great database design but allows for any data to be stored about a person. 

I am looking forward to getting this going with a pull request or two but any wondering what everyone thinks is the better way to go

**Comment by issmirnov** [comment]
What do you think about #79?

**Comment by the94air** [comment]
@degan6 @issmirnov It looks like it is a grate idea. This way the user have the freedom of adding the proper details for any person. nice work guys. :+1: . I personally support the Idea.  
  
An other thing I would like to separate All the forms error message for each input instead of echoing out all the messages like this
![errors](https://user-images.githubusercontent.com/18303390/26867339-a387349a-4b6d-11e7-8f4e-c3cc8bc5c8fe.png)
Is it Ok. I would make a PR.

**Comment by mkaz** [comment]
A great resource for data too is Gravatar which if you have someone's email address can pull in any information they have published there beyond their photo, for example websites and social accounts

Here's an example for my account: https://en.gravatar.com/mkaz.json

Would need the fields and then it would be pretty straight-forward to pull in the data when initially creating the Contact once the email is entered to help fill out the form.

**Comment by djaiss** [comment]
I think this, like #79 , should be handled very carefully. Before moving forward with a PR for this, let's discuss how we can achieve this, because the product has to remain extremely simple.

**Comment by degan6** [comment]
I agree, I think #79 has a better discussion and more fleshed out ideas for how to get it done. I'm going to close this out as a dub.

**Comment by degan6** [comment]
Dub of #79
