### ISSUE TITLE
Ugly config

### ISSUE THREAD

**Issue by asbiin** [monicahq/monica#872]
in config/sentry.php:
```
...
    // capture release as git sha
    'release' => trim(exec('git log --pretty="%h" -n1 HEAD')),
...
```
This is ugly. We don't want to publish .git directory in production, but this line is executed each time "php artisan" is called.
Is this still needed ?

**Comment by djaiss** [comment]
@asbiin this is what allows Sentry to catch the error and tell which version of the code was it running against.
But we don't need it at all since production runs the latest version all the time.
So we can either remove the line or make it blank. Perhaps making it blank is better as I don't know how sentry would handle a missing config parameter.

**Comment by tomzx** [comment]
This would be a good candidate for a build/deploy-time variable. After the git repository has been updated on the production machine, run the `git log ...` command once in order to obtain the value and put it in the `.env` file for instance.

**Comment by asbiin** [comment]
What do you think of:
```
...
    // capture release as git sha
    'release' => trim(exec('test -d '.__DIR__.'/../.git && git log --pretty="%h" -n1 HEAD')),
...
```

**Comment by asbiin** [comment]
@tomzx problem is when running the `git log` command ?
On heroku for instance, composer is running on a not git repository. The log command must be run with `git clone`, but we do not have the hand on it ...

**Comment by tomzx** [comment]
@asbiin My main concern is having an `exec` call on every page load. Correct me if I'm mistaken, but laravel will load all the configuration files on each page load, and thus will execute the command every time.
