### ISSUE TITLE
error when running in "production" mode 

### ISSUE THREAD

**Issue by lordhippo93** [monicahq/monica#899]
it was running fine, then i went to update and it started throwing errors about "dusk" something. ("dusk" is something new for this update right?)
"It is unsafe to run Dusk in production."

so turned of "production" mode, and the update went fine. turned it back on again because for me it solves the "SSL behind proxy" stuff. and back comes the errors... so i turn on debug mode and find the error, the same from before. and where it is. :)

/var/www/monica/vendor/laravel/dusk/src/DuskServiceProvider.php
if ($this->app->environment('production')) {
            throw new Exception('It is unsafe to run Dusk in production.');
        }

so just removed that line of code and its working full steam again.

i have no idé what "dusk" is... so i hope this helps and i have not broken something else for my self x)

p.s first time submitting issue on github, hope i dident do to badly in explaining the problem :) d.s

pp.s Love this project! <3 d.s

**Comment by djaiss** [comment]
Dusk is a front end testing framework that should never, ever run in production.
I've noticed that in some setup, composer doesn't work when Dusk is in composer.json (even in the `require-dev` section).

One workaround is to run `composer update --no-dev` instead of `composer update`.

@asbiin do you have errors when you do a `composer` now? I do in Fortrabbit and I think I'll have the same issue in Forge.

**Comment by asbiin** [comment]
@djaiss  what is your error output ? Tests on travis are currently running `composer install --no-dev` and `composer install` without any issue.

**Comment by asbiin** [comment]
Everything is fine on travis
