### ISSUE TITLE
Dashboard broken in production

### ISSUE THREAD

**Issue by ThatCarterMcBride** [monicahq/monica#988]
I can navigate just fine to "Settings", "Contacts", "Journal", etc, but if I go to dashboard, all it displays is "Whoops, something went wrong."

It has been like this for 4 days.
I've tried restart, clearing the cache, logging out and logging back in, and trying a difference browser.
There are no errors in the console.

**Comment by asbiin** [comment]
What version of monica are you using ?

**Comment by ThatCarterMcBride** [comment]
It is the hosted version (monicahq.com), so version 1.8.1.
Strange thing is, I made a new account and everything worked. It is just the dashboard and just on this account.
There are only 6 contacts with basic information.
Could it be some corrupted contact information?

**Comment by djaiss** [comment]
Really sorry about this and sorry for my lack of answer (was on holidays). I'm going to check that in a few hours.

**Comment by ThatCarterMcBride** [comment]
Any update on this?

**Comment by djaiss** [comment]
Trying to debug this.

This is really strange. You have a user account on the platform, but you don't have any `account_id`, which is really strange.

Have you reset your account once already?

**Comment by djaiss** [comment]
Actually you do have an `account_id`, but the Account object doesn't exist.

I don't understand why this happened. But this is not isolated - we have 304 users who have the same problem as you. I need to fully review the codebase to see how Monica can delete an Account object without having the user account deleted as well. I'm really sorry about this. The best solution for now is to create a new account, if you can - until I find the solution to this problem.

Also, because we don't have a valid `account_id`, I can't know which contacts belong to you.

**Comment by djaiss** [comment]
Closing due to a lack of activity.
